import json

with open("scripts/m2v8_cues.json", "r", encoding="utf-8") as f:
    cues = json.load(f)

# English translations matching exact index 1..106
en_translations = {
    1: "Peace be upon you, and welcome to the eighth video of our fellowship.",
    2: "In our previous journey, we looked at the bigger picture of health and saw how housing quality, air purity, and harsh heatwaves hit the most vulnerable groups.",
    3: "Honestly, the scene is immense, the challenges are intimidating and daunting, leaving one pondering: what next, and where do I fit in this complex picture?",
    4: "Let us delve a bit deeper into the question: Can a single person really make a difference against crises threatening an entire planet?",
    5: "Feeling helpless here is completely natural; it makes you feel like a drop in the ocean.",
    6: "Yet the truth we will discover now will completely transform our perception of our impact.",
    7: "To make a real difference, we don't need to be doctors wearing lab coats and stethoscopes,",
    8: "nor scientists sitting in laboratories analyzing atmospheric physics.",
    9: "The real power to save lives is not confined within operating rooms and hospitals.",
    10: "Real change begins right from the street, using simple, smart tools.",
    11: "The problem in our world today is not a lack of research.",
    12: "Medical research papers are published by the thousands every single day,",
    13: "and climate reports fill whole volumes.",
    14: "The real dilemma is the fatal gap between this research and the community.",
    15: "A massive library packed with reports, facing a residential neighborhood drowning in rumors and health hazards while nobody understands a thing.",
    16: "Knowledge alone does not save lives,",
    17: "if it remains locked away in drawers and conference halls.",
    18: "What truly makes a difference",
    19: "is reaching people at the right moment,",
    20: "in a language they easily understand,",
    21: "and applying it in their daily routines.",
    22: "Here is precisely where your role as a community health educator comes in.",
    23: "You are the human bridge.",
    24: "On one side stands an ivory tower filled",
    25: "with complex, tangled Latin terminology,",
    26: "and on the other side,",
    27: "ordinary people living through their daily routines and challenges.",
    28: "The health educator",
    29: "stands right in the middle of that bridge,",
    30: "decoding this complex science",
    31: "and articulating it in warm, simple words,",
    32: "understood by workers at construction sites,",
    33: "mothers in their homes,",
    34: "and grandmothers caring for their grandchildren.",
    35: "They are the ones turning theories into the pulse of real life on the ground.",
    36: "Yet for this bridge to remain solid and trusted,",
    37: "it must be founded on strict professional boundaries.",
    38: "Your role focuses on simplifying science,",
    39: "empowering people,",
    40: "and instilling preventive habits.",
    41: "However, there are red lines",
    42: "you must never cross.",
    43: "There is no such thing as diagnosing diseases,",
    44: "prescribing medications, adjusting dosages, or offering personalized clinical consultations on your own.",
    45: "You are there to raise awareness,",
    46: "not act like an anesthesiologist or general surgeon on the side.",
    47: "Respecting these boundaries is the pinnacle of professionalism and integrity that protects both the public and your credibility.",
    48: "So, how do we apply this to climate and health issues?",
    49: "People don't need you to explain the Paris Climate Agreement,",
    50: "nor do they need you to explain dry carbon emission metrics.",
    51: "People need answers to questions that directly touch their lives:",
    52: "How does this extreme heat affect our children?",
    53: "How do we protect our elderly and those with chronic illnesses",
    54: "when a dust storm hits or the power cuts out?",
    55: "Your role is to translate a planetary crisis into localized, actionable steps",
    56: "that protect bodies and build resilient communities capable of enduring.",
    57: "Let us look at a practical scenario:",
    58: "The moment weather services forecast an exceptional heatwave,",
    59: "the health educator does not just sit and watch.",
    60: "They launch a proactive emergency plan:",
    61: "publishing visual alerts on heatstroke symptoms,",
    62: "heading out into the field to host interactive awareness sessions,",
    63: "checking on the elderly and those with chronic conditions,",
    64: "and coordinating with schools and workshops to provide cold water and shaded rest breaks for workers.",
    65: "Through these steps, you have built a safety net;",
    66: "you have spared hospitals hundreds of emergency admissions.",
    67: "To be truly influential, our tools must be agile and modern.",
    68: "In the past, whenever health education was mentioned,",
    69: "one envisioned a lifeless lecture where someone read off slides",
    70: "to a hall full of sleeping, snoring audiences.",
    71: "Today, awareness has become vastly smarter:",
    72: "a short TikTok video",
    73: "debunking a myth in half a minute,",
    74: "an infographic summarizing preventive steps at a single glance,",
    75: "an interactive workshop with neighborhood mothers",
    76: "sharing practical experiences in healthy cooking,",
    77: "an engaging school activity",
    78: "teaching children to drink water through fun and storytelling,",
    79: "or a youth initiative distributing water",
    80: "and setting up shaded spots around midday.",
    81: "To manage these tools properly, you need five core skills:",
    82: "Scientific understanding: obtaining accurate information from verified sources;",
    83: "Impactful communication: speaking in a way that resonates with both mind and heart;",
    84: "Community mindset: listening to people and understanding grassroots field needs;",
    85: "Content creation: writing smart scripts and employing visual media professionally;",
    86: "Leadership and initiative: transforming ideas into tangible, sustainable projects on the ground.",
    87: "Yet let us pause for a moment and reflect deeply:",
    88: "Success in health education was never measured by how many posts you publish,",
    89: "nor by the number of likes and shares you rack up.",
    90: "The true yardstick is actual impact,",
    91: "and how capable you are of turning an idea into tangible preventive behavior that genuinely protects people's lives.",
    92: "The takeaway we have built throughout this module:",
    93: "A community health educator is neither a treating physician nor a policymaker locked in an office;",
    94: "they are an enabler of people,",
    95: "the first line of defense simplifying science and instilling prevention,",
    96: "building a resilient community that stands firmly in the face of climate crises.",
    97: "Now that our conceptual foundation is solid and sound,",
    98: "we are completely ready to take action.",
    99: "Before we sign off, we want to leave you with this practical reflection:",
    100: "Look around your neighborhood or university campus:",
    101: "What pressing health or climate issue exists right now?",
    102: "Who is the most vulnerable group at risk?",
    103: "And what digital content or field campaign",
    104: "can you launch to protect them?",
    105: "Always remember: knowledge holds no value unless it reaches the people who need it most.",
    106: "Thank you for watching, and see you in the next video!"
}

assert len(en_translations) == len(cues) == 106, f"Mismatch: {len(en_translations)} vs {len(cues)}"

output_lines = ["WEBVTT\n"]
for c in cues:
    idx = c["index"]
    timing = c["timing"]
    en_text = en_translations[idx]
    output_lines.append(f"{idx}\n{timing}\n{en_text}\n")

with open("scripts/subtitles_en/m2v8.vtt", "w", encoding="utf-8") as f:
    f.write("\n".join(output_lines).strip() + "\n")

print("Successfully generated m2v8.vtt in English with exactly 106 cues!")
