import json

with open("scripts/m2v9_cues.json", "r", encoding="utf-8") as f:
    cues = json.load(f)

en_translations = {
    1: "Peace be upon you, and welcome to the final video of the second module in our fellowship.",
    2: "Our session today isn't merely another lecture to add to our notes and call it a day.",
    3: "This is a comprehensive intellectual upgrade to our mindset and way of thinking as health professionals and leaders.",
    4: "Any ordinary person looking at disease spreading in a neighborhood might say: 'Good grief, bad luck, or some airborne bacteria messing with people.'",
    5: "Yet we are here to completely transform that perspective.",
    6: "We want to understand how a public health researcher and leader perceives the world through different lenses,",
    7: "deconstructing complex phenomena with scientific, professional tools that unveil what lies beneath the surface.",
    8: "To achieve this mental upgrade, our roadmap today begins with the mindset of the public health researcher.",
    9: "Public health does not rely on a single, narrow lens;",
    10: "it is grounded in a robust framework of theoretical models.",
    11: "It is like assembling a grand puzzle: a lens examining the body, a lens probing psychology, a lens observing society, and a lens studying environment, policy, and law.",
    12: "These models are not mere ink on paper left in drawers; they are the compass answering three existential questions:",
    13: "Why does disease emerge in this specific neighborhood while another is spared? Why is there inequality in people's resilience against climate impacts?",
    14: "And how do we design radical interventions that address the root cause of the problem,",
    15: "rather than merely applying bandages and temporary pain relievers?",
    16: "The models from individual to society:",
    17: "The first revolutionary breakthrough in modern medical thought",
    18: "was breaking away from the outdated view that treated the human being",
    19: "like a broken washing machine or engine,",
    20: "to be fixed with a pill and some brake fluid.",
    21: "Then came the Biopsychosocial Model,",
    22: "affirming that health is not merely chemical reactions,",
    23: "but an ongoing interplay across three dimensions:",
    24: "The biological dimension: genetics, thermoregulation, blood pressure, and immunity;",
    25: "the psychological dimension: showcasing stress, nervous anxiety, and eco-anxiety;",
    26: "and finally the social dimension: income, education, housing quality, and healthcare access.",
    27: "Let us apply this to climate realities:",
    28: "During a severe heatwave, biologically the body loses fluids and blood pressure drops;",
    29: "psychologically, irritability kicks in, sleep deprivation mounts, and stress escalates;",
    30: "socially, domestic tensions and friction intensify at home,",
    31: "and the elderly become isolated in un-airconditioned houses.",
    32: "Here, the health educator does not just say 'drink water';",
    33: "rather, they recognize that psychosocial support is integral to bodily survival.",
    34: "When analyzing human behaviors and actions,",
    35: "we possess another ingenious tool:",
    36: "The Socio-Ecological Model (SEM).",
    37: "This framework shatters the myth that human behavior stems purely from isolated free will.",
    38: "Our decisions are enveloped within five nested circles, like the layers of an onion:",
    39: "starting with the individual and their knowledge,",
    40: "expanding to interpersonal relationships,",
    41: "then organizational structures,",
    42: "broadening to community and cultural norms,",
    43: "and culminating in the outer ring:",
    44: "public policies and governance.",
    45: "Imagine protecting construction workers from heat exhaustion:",
    46: "At the individual level: the worker knows they must hydrate and seek shade.",
    47: "At the relational level: if his peers on site ridicule him saying, 'What a pampered guy, can't handle the heat?',",
    48: "he will endanger his life just to avoid appearing weak.",
    49: "At the institutional level: has the contractor provided shaded canopies and drinking water on site, or not?",
    50: "At the community level: does the neighborhood even provide public water points for passersby?",
    51: "And at the policy level: have the municipality and labor ministry issued mandatory bans on peak-hour work with penalties for violators?",
    52: "If you only educate the worker in isolation, it is like telling them to swim against a tsunami.",
    53: "Real change touches all five tiers concurrently.",
    54: "Now we move to our third milestone: determinants and levels of prevention.",
    55: "The Social Determinants of Health (SDOH) model reminds us of the striking truth:",
    56: "human health is shaped far more by daily living conditions than by operating theaters.",
    57: "The inequitable distribution of resources is the factory of health disparities.",
    58: "In climate crises, those with financial stability dwell in thermally insulated homes,",
    59: "can afford the air conditioning bill, and drink filtered water in peace;",
    60: "meanwhile, someone living under corrugated zinc roofs in an informal settlement cannot afford a fan, and their water comes from tankers vulnerable to runoff contamination during the first rains.",
    61: "The health educator knows that their health crusade is inseparable from social justice.",
    62: "Here comes the prevention pyramid: when do we intervene?",
    63: "As we discussed in earlier videos:",
    64: "Primary prevention: we eradicate the hazard at its roots before it approaches the body;",
    65: "we afforest neighborhoods,",
    66: "paint rooftops with reflective white paint,",
    67: "and deploy early warning systems 3 days ahead of heatwaves.",
    68: "Secondary prevention: here we race against time to detect hazard at its inception;",
    69: "screening workers for dizziness and headache symptoms,",
    70: "cooling them down before they collapse into heatstroke comas,",
    71: "and assessing children's respiratory function the moment dust storms strike.",
    72: "Tertiary prevention: when disaster strikes,",
    73: "we intervene inside hospitals to prevent mortality and alleviate complications of renal failure and cardiac arrest alongside rehabilitation.",
    74: "Our greatest arena as educators is the primary and secondary levels:",
    75: "building ramparts of safety in the community before individuals reach intensive care.",
    76: "In our fourth stop, we zoom out to the maximum scale,",
    77: "encompassing the entire planet:",
    78: "The One Health framework.",
    79: "This model proves that human, animal, and environmental health",
    80: "form a single umbilical cord and an indivisible fabric.",
    81: "Over 60% of hazardous infectious diseases",
    82: "are zoonotic in origin,",
    83: "spilling over to us through deforestation,",
    84: "unplanned urban expansion, and wildlife trafficking.",
    85: "When climate shifts alter temperatures and precipitation patterns,",
    86: "mosquitoes, ticks, and sandflies expand their habitats,",
    87: "transmitting dengue, malaria, and leishmaniasis",
    88: "into entirely new regions.",
    89: "We cannot protect a child from dengue fever",
    90: "while open sewage drainage and breeding swamps",
    91: "saturate the neighborhood and degrade the environment.",
    92: "Human health begins with planetary preservation.",
    93: "In our fifth milestone,",
    94: "we zoom in on the engineering of change:",
    95: "health behavior change models,",
    96: "such as the Health Belief Model (HBM).",
    97: "Never fall into the trap of believing",
    98: "that knowledge alone suffices to induce change.",
    99: "No matter how often we reiterate this across our fellowship,",
    100: "you must always keep it in mind:",
    101: "every smoker knows smoking causes cancer,",
    102: "and every victim of heatstroke knows the sun is scorching.",
    103: "Behavior change demands perceived threat:",
    104: "feeling that the hazard impacts them personally and harms their children;",
    105: "self-efficacy: believing in one's capacity to adopt the behavior,",
    106: "knowing it is neither complicated nor costly;",
    107: "breaking barriers:",
    108: "pointing them toward affordable home-based remedies,",
    109: "instead of prescribing filters costing fortunes.",
    110: "And now we reach the pinnacle:",
    111: "Integrative Diagnosis:",
    112: "assembling the puzzle pieces before the construction worker heatstroke crisis.",
    113: "Here we look through the Biopsychosocial lens,",
    114: "to observe dehydration physiology coupled with the worker's fear of losing daily wages and impoverishment.",
    115: "We expand through SEM,",
    116: "to observe peer pressure on site, contractor greed, and absence of municipal oversight.",
    117: "We apply SDOH,",
    118: "recognizing he only risked his life to put food on the table for his children.",
    119: "We then invoke the Prevention Pyramid,",
    120: "rejecting reliance merely on tertiary ambulance responses,",
    121: "and demanding mandatory shaded shelters and breaks, which constitute primary prevention.",
    122: "We connect through One Health, observing how lack of urban tree canopy and excess asphalt",
    123: "spawned urban heat islands suffocating the work site.",
    124: "And we deploy Behavioral Models to train workers to recognize dizziness symptoms",
    125: "and drink water without hesitation.",
    126: "This is how a public health leader thinks with a 360-degree vision.",
    127: "In summary: public health is not merely disjointed advice;",
    128: "it is a comprehensive thought architecture.",
    129: "We do not treat superficial symptoms;",
    130: "we deconstruct the interplay of body and mind,",
    131: "society,",
    132: "equitable resources,",
    133: "and climate.",
    134: "With this rigorous foundation,",
    135: "we officially draw the curtain",
    136: "on the entirety of Module Two.",
    137: "You now possess the solid intellectual bedrock",
    138: "to serve as authentic leaders.",
    139: "We leave you with this practical exercise:",
    140: "Consider the surge in childhood asthma exacerbations",
    141: "during sandstorms",
    142: "and heatwaves in your local neighborhood:",
    143: "How do you apply the SEM across family, school, and policy levels?",
    144: "What intervention constitutes primary prevention, and what constitutes secondary prevention?",
    145: "And how do you utilize the One Health principle to interpret the rising frequency of sandstorms",
    146: "in relation to overgrazing and vegetation degradation?",
    147: "Thank you for watching,",
    148: "and heartfelt congratulations on completing Module Two!",
    149: "We will see you in Module Three with utmost determination and passion!"
}

assert len(en_translations) == len(cues) == 149, f"Mismatch: {len(en_translations)} vs {len(cues)}"

output_lines = ["WEBVTT\n"]
for c in cues:
    idx = c["index"]
    timing = c["timing"]
    en_text = en_translations[idx]
    output_lines.append(f"{idx}\n{timing}\n{en_text}\n")

with open("scripts/subtitles_en/m2v9.vtt", "w", encoding="utf-8") as f:
    f.write("\n".join(output_lines).strip() + "\n")

print("Successfully generated m2v9.vtt in English with exactly 149 cues!")
